### ISSUE TITLE
Monitoring Results Summary

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#876]
Summary of #477 

Use https://github.com/coreos/prometheus-operator 

> CustomResourceDefinitions
> 
> The Operator acts on the following custom resource definitions (CRDs):
> 
> Prometheus, which defines a desired Prometheus deployment. The Operator ensures at all times that a deployment matching the resource definition is running.
> 
> ServiceMonitor, which declaratively specifies how groups of services should be monitored. The Operator automatically generates Prometheus scrape configuration based on the definition.
> 
> Alertmanager, which defines a desired Alertmanager deployment. The Operator ensures at all times that a deployment matching the resource definition is running.

Based on this fully configured setup: https://github.com/camilb/prometheus-kubernetes
(in the /operator subdirectory).   (note: it also appears that work is being pulled into a coreos repo).

This is an umbrella issue for the work needed.

- [ ] create by hand full up monitor/alert system based on the above repos using `prometheus-operator` and all its parts. #884
- [ ] create monitoring setup for external etcd (nodes and services) #885
- [ ] determine correct way to dynamically change alerting and monitoring set up - may need to create a small web client/server to do this nicely. #890
- [ ] fix kubernetes timeout so `proxy-forward` is viable #887
- [ ] determine correct safe way to connect to dashboards, and control access to dashboards. #886
- [ ] create repo for finished product #888
- [ ] create helm charts if possible, otherwise script the setup #889

**Comment by mikeln** [comment]
Sub issues created and linked.

**Comment by coffeepac** [comment]
moved to samsung-cnct/kraken-lib#77
